/**
 * Kie.ai Models Configuration
 */

import { KieModel } from "./types";

// ==================== Image Models ====================

export const IMAGE_MODELS: KieModel[] = [
  {
    id: "google-imagen4",
    name: "Google Imagen4",
    nameRu: "Google Imagen4",
    category: "image",
    type: "text-to-image",
    description: "State-of-the-art image generation",
    descriptionRu: "Передовая генерация изображений от Google",
    modelId: "google/imagen4",
    icon: "🎨",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true, placeholderRu: "Опишите изображение..." },
      { name: "negative_prompt", label: "Negative Prompt", labelRu: "Негативный промпт", type: "textarea", required: false, placeholderRu: "Что исключить..." },
      { name: "aspect_ratio", label: "Aspect Ratio", labelRu: "Соотношение сторон", type: "select", required: false, options: [
        { value: "1:1", label: "1:1", labelRu: "1:1 Квадрат" },
        { value: "16:9", label: "16:9", labelRu: "16:9 Альбом" },
        { value: "9:16", label: "9:16", labelRu: "9:16 Портрет" },
        { value: "4:3", label: "4:3", labelRu: "4:3 Стандарт" },
        { value: "3:4", label: "3:4", labelRu: "3:4 Вертикаль" },
        { value: "3:2", label: "3:2", labelRu: "3:2 Фото" },
        { value: "2:3", label: "2:3", labelRu: "2:3 Портрет" },
        { value: "21:9", label: "21:9", labelRu: "21:9 Кино" },
      ], defaultValue: "1:1" },
      { name: "resolution", label: "Resolution", labelRu: "Разрешение", type: "select", required: false, options: [
        { value: "1024", label: "1K (1024px)", labelRu: "1K (1024px)" },
        { value: "2048", label: "2K (2048px)", labelRu: "2K (2048px)" },
        { value: "3072", label: "3K (3072px)", labelRu: "3K (3072px)" },
        { value: "4096", label: "4K (4096px)", labelRu: "4K (4096px)" },
      ], defaultValue: "1024" },
      { name: "output_format", label: "Format", labelRu: "Формат", type: "select", required: false, options: [
        { value: "png", label: "PNG", labelRu: "PNG" },
        { value: "jpg", label: "JPG", labelRu: "JPG" },
        { value: "webp", label: "WebP", labelRu: "WebP" },
      ], defaultValue: "png" },
      { name: "num_images", label: "Number of Images", labelRu: "Количество", type: "select", required: false, options: [
        { value: "1", label: "1", labelRu: "1" },
        { value: "2", label: "2", labelRu: "2" },
        { value: "4", label: "4", labelRu: "4" },
      ], defaultValue: "1" },
    ],
  },
  {
    id: "google-imagen4-ultra",
    name: "Google Imagen4 Ultra",
    nameRu: "Google Imagen4 Ultra",
    category: "image",
    type: "text-to-image",
    description: "Highest quality image generation",
    descriptionRu: "Генерация изображений высочайшего качества",
    modelId: "google/imagen4-ultra",
    icon: "✨",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true, placeholderRu: "Опишите изображение..." },
      { name: "negative_prompt", label: "Negative Prompt", labelRu: "Негативный промпт", type: "textarea", required: false },
      { name: "aspect_ratio", label: "Aspect Ratio", labelRu: "Соотношение сторон", type: "select", required: false, options: [
        { value: "1:1", label: "1:1", labelRu: "1:1 Квадрат" },
        { value: "16:9", label: "16:9", labelRu: "16:9 Альбом" },
        { value: "9:16", label: "9:16", labelRu: "9:16 Портрет" },
        { value: "4:3", label: "4:3", labelRu: "4:3 Стандарт" },
        { value: "3:4", label: "3:4", labelRu: "3:4 Вертикаль" },
        { value: "21:9", label: "21:9", labelRu: "21:9 Кино" },
      ], defaultValue: "1:1" },
      { name: "resolution", label: "Resolution", labelRu: "Разрешение", type: "select", required: false, options: [
        { value: "1024", label: "1K", labelRu: "1K (1024px)" },
        { value: "2048", label: "2K", labelRu: "2K (2048px)" },
        { value: "4096", label: "4K", labelRu: "4K (4096px)" },
      ], defaultValue: "1024" },
      { name: "output_format", label: "Format", labelRu: "Формат", type: "select", required: false, options: [
        { value: "png", label: "PNG", labelRu: "PNG" },
        { value: "jpg", label: "JPG", labelRu: "JPG" },
      ], defaultValue: "png" },
    ],
  },
  {
    id: "google-nano-banana-pro",
    name: "Google Nano Banana Pro",
    nameRu: "Google Nano Banana Pro",
    category: "image",
    type: "text-to-image",
    description: "Gemini 3.0 Pro Image - 4K high-fidelity rendering",
    descriptionRu: "Gemini 3.0 Pro Image — 4K генерация высокого качества",
    modelId: "nano-banana-pro",
    icon: "🍌",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true, placeholderRu: "Опишите изображение детально..." },
      { name: "aspect_ratio", label: "Aspect Ratio", labelRu: "Соотношение сторон", type: "select", required: false, options: [
        { value: "1:1", label: "1:1", labelRu: "1:1 Квадрат" },
        { value: "16:9", label: "16:9", labelRu: "16:9 Широкий" },
        { value: "9:16", label: "9:16", labelRu: "9:16 Мобильный" },
        { value: "4:3", label: "4:3", labelRu: "4:3 Стандарт" },
        { value: "3:4", label: "3:4", labelRu: "3:4 Портрет" },
        { value: "3:2", label: "3:2", labelRu: "3:2 Фото" },
        { value: "2:3", label: "2:3", labelRu: "2:3 Вертикаль" },
        { value: "21:9", label: "21:9", labelRu: "21:9 Кино" },
        { value: "9:21", label: "9:21", labelRu: "9:21 Высокий" },
        { value: "4:5", label: "4:5", labelRu: "4:5 Instagram" },
        { value: "5:4", label: "5:4", labelRu: "5:4 Альбом" },
      ], defaultValue: "1:1" },
      { name: "resolution", label: "Resolution", labelRu: "Разрешение", type: "select", required: false, options: [
        { value: "1K", label: "1K ($0.09)", labelRu: "1K ($0.09)" },
        { value: "2K", label: "2K ($0.09)", labelRu: "2K ($0.09)" },
        { value: "4K", label: "4K ($0.12)", labelRu: "4K ($0.12)" },
      ], defaultValue: "1K" },
      { name: "output_format", label: "Format", labelRu: "Формат", type: "select", required: false, options: [
        { value: "png", label: "PNG", labelRu: "PNG" },
        { value: "jpg", label: "JPG", labelRu: "JPG" },
        { value: "webp", label: "WebP", labelRu: "WebP" },
      ], defaultValue: "png" },
    ],
  },
  {
    id: "google-nano-banana-edit",
    name: "Google Nano Banana Edit",
    nameRu: "Google Nano Banana Edit",
    category: "image",
    type: "image-edit",
    description: "Edit images with Gemini 3.0 Pro - 4K support",
    descriptionRu: "Редактирование изображений с Gemini 3.0 Pro — 4K",
    modelId: "nano-banana-pro",
    icon: "✏️",
    inputFields: [
      { name: "image_input", label: "Image", labelRu: "Изображение", type: "file", required: true },
      { name: "prompt", label: "Edit Prompt", labelRu: "Промпт редактирования", type: "textarea", required: true, placeholderRu: "Опишите что нужно изменить на изображении..." },
      { name: "aspect_ratio", label: "Aspect Ratio", labelRu: "Соотношение сторон", type: "select", required: false, options: [
        { value: "1:1", label: "1:1", labelRu: "1:1 Квадрат" },
        { value: "16:9", label: "16:9", labelRu: "16:9 Широкий" },
        { value: "9:16", label: "9:16", labelRu: "9:16 Мобильный" },
        { value: "4:3", label: "4:3", labelRu: "4:3 Стандарт" },
        { value: "3:4", label: "3:4", labelRu: "3:4 Портрет" },
        { value: "3:2", label: "3:2", labelRu: "3:2 Фото" },
        { value: "2:3", label: "2:3", labelRu: "2:3 Вертикаль" },
        { value: "21:9", label: "21:9", labelRu: "21:9 Кино" },
        { value: "9:21", label: "9:21", labelRu: "9:21 Высокий" },
        { value: "4:5", label: "4:5", labelRu: "4:5 Instagram" },
        { value: "5:4", label: "5:4", labelRu: "5:4 Альбом" },
      ], defaultValue: "1:1" },
      { name: "resolution", label: "Resolution", labelRu: "Разрешение", type: "select", required: false, options: [
        { value: "1K", label: "1K ($0.09)", labelRu: "1K ($0.09)" },
        { value: "2K", label: "2K ($0.09)", labelRu: "2K ($0.09)" },
        { value: "4K", label: "4K ($0.12)", labelRu: "4K ($0.12)" },
      ], defaultValue: "1K" },
      { name: "output_format", label: "Format", labelRu: "Формат", type: "select", required: false, options: [
        { value: "png", label: "PNG", labelRu: "PNG" },
        { value: "jpg", label: "JPG", labelRu: "JPG" },
        { value: "webp", label: "WebP", labelRu: "WebP" },
      ], defaultValue: "png" },
    ],
  },
  {
    id: "flux2-pro",
    name: "Flux-2 Pro",
    nameRu: "Flux-2 Pro",
    category: "image",
    type: "text-to-image",
    description: "Advanced text-to-image generation",
    descriptionRu: "Продвинутая генерация изображений",
    modelId: "flux2/pro-text-to-image",
    icon: "⚡",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true },
      { name: "aspect_ratio", label: "Aspect Ratio", labelRu: "Соотношение сторон", type: "select", required: false, options: [
        { value: "1:1", label: "1:1", labelRu: "1:1 Квадрат" },
        { value: "16:9", label: "16:9", labelRu: "16:9 Альбом" },
        { value: "9:16", label: "9:16", labelRu: "9:16 Портрет" },
        { value: "4:3", label: "4:3", labelRu: "4:3 Стандарт" },
        { value: "3:4", label: "3:4", labelRu: "3:4 Вертикаль" },
        { value: "21:9", label: "21:9", labelRu: "21:9 Кино" },
      ], defaultValue: "1:1" },
      { name: "resolution", label: "Resolution", labelRu: "Разрешение", type: "select", required: false, options: [
        { value: "1024", label: "1K", labelRu: "1K (1024px)" },
        { value: "2048", label: "2K", labelRu: "2K (2048px)" },
        { value: "4096", label: "4K", labelRu: "4K (4096px)" },
      ], defaultValue: "1024" },
      { name: "output_format", label: "Format", labelRu: "Формат", type: "select", required: false, options: [
        { value: "png", label: "PNG", labelRu: "PNG" },
        { value: "jpg", label: "JPG", labelRu: "JPG" },
      ], defaultValue: "png" },
      { name: "guidance_scale", label: "Guidance Scale", labelRu: "Сила направления", type: "slider", required: false, min: 1, max: 20, step: 0.5, defaultValue: 7.5 },
    ],
  },
  {
    id: "topaz-upscale",
    name: "Topaz Upscale",
    nameRu: "Topaz Увеличение",
    category: "image",
    type: "upscale",
    description: "AI-powered image upscaling",
    descriptionRu: "ИИ увеличение изображений",
    modelId: "topaz/image-upscale",
    icon: "🔍",
    inputFields: [
      { name: "image_url", label: "Image", labelRu: "Изображение", type: "file", required: true },
      { name: "scale", label: "Scale", labelRu: "Масштаб", type: "select", required: false, options: [
        { value: "2", label: "2x", labelRu: "2x" },
        { value: "4", label: "4x", labelRu: "4x" },
      ], defaultValue: "2" },
    ],
  },
  {
    id: "recraft-upscale",
    name: "Recraft Upscale",
    nameRu: "Recraft Увеличение",
    category: "image",
    type: "upscale",
    description: "Professional image upscaling",
    descriptionRu: "Профессиональное увеличение",
    modelId: "recraft/crisp-upscale",
    icon: "📐",
    inputFields: [
      { name: "image_url", label: "Image", labelRu: "Изображение", type: "file", required: true },
    ],
  },
  {
    id: "recraft-remove-bg",
    name: "Recraft Remove Background",
    nameRu: "Recraft Удаление фона",
    category: "image",
    type: "background-removal",
    description: "Remove background from images",
    descriptionRu: "Удаление фона с изображений",
    modelId: "recraft/remove-background",
    icon: "🎭",
    inputFields: [
      { name: "image_url", label: "Image", labelRu: "Изображение", type: "file", required: true },
    ],
  },
  {
    id: "ideogram-v3",
    name: "Ideogram v3",
    nameRu: "Ideogram v3",
    category: "image",
    type: "text-to-image",
    description: "Creative image generation with text rendering",
    descriptionRu: "Креативная генерация с отрисовкой текста",
    modelId: "ideogram/v3-text-to-image",
    icon: "💡",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true },
      { name: "style", label: "Style", labelRu: "Стиль", type: "select", required: false, options: [
        { value: "AUTO", label: "Auto", labelRu: "Авто" },
        { value: "REALISTIC", label: "Realistic", labelRu: "Реалистичный" },
        { value: "DESIGN", label: "Design", labelRu: "Дизайн" },
        { value: "RENDER_3D", label: "3D Render", labelRu: "3D Рендер" },
        { value: "ANIME", label: "Anime", labelRu: "Аниме" },
      ], defaultValue: "AUTO" },
      { name: "rendering_speed", label: "Quality", labelRu: "Качество", type: "select", required: false, options: [
        { value: "BALANCED", label: "Balanced", labelRu: "Баланс" },
        { value: "FAST", label: "Fast", labelRu: "Быстро" },
        { value: "QUALITY", label: "Quality", labelRu: "Качество" },
      ], defaultValue: "BALANCED" },
      { name: "image_size", label: "Size", labelRu: "Размер", type: "select", required: false, options: [
        { value: "square_hd", label: "1:1 HD", labelRu: "1:1 Квадрат HD" },
        { value: "square_4k", label: "1:1 4K", labelRu: "1:1 Квадрат 4K" },
        { value: "landscape_16_9", label: "16:9", labelRu: "16:9 Альбом" },
        { value: "landscape_16_9_4k", label: "16:9 4K", labelRu: "16:9 Альбом 4K" },
        { value: "portrait_9_16", label: "9:16", labelRu: "9:16 Портрет" },
        { value: "portrait_9_16_4k", label: "9:16 4K", labelRu: "9:16 Портрет 4K" },
      ], defaultValue: "square_hd" },
      { name: "output_format", label: "Format", labelRu: "Формат", type: "select", required: false, options: [
        { value: "png", label: "PNG", labelRu: "PNG" },
        { value: "jpg", label: "JPG", labelRu: "JPG" },
      ], defaultValue: "png" },
    ],
  },
  {
    id: "ideogram-v3-reframe",
    name: "Ideogram v3 Reframe",
    nameRu: "Ideogram v3 Рефрейм",
    category: "image",
    type: "reframe",
    description: "Reframe images with AI",
    descriptionRu: "Изменение рамки изображения",
    modelId: "ideogram/v3-reframe",
    icon: "🖼️",
    inputFields: [
      { name: "image_url", label: "Image", labelRu: "Изображение", type: "file", required: true },
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true },
      { name: "aspect_ratio", label: "Target Aspect Ratio", labelRu: "Целевое соотношение", type: "select", required: false, options: [
        { value: "1:1", label: "Square", labelRu: "Квадрат" },
        { value: "16:9", label: "Landscape", labelRu: "Альбом" },
        { value: "9:16", label: "Portrait", labelRu: "Портрет" },
      ], defaultValue: "16:9" },
    ],
  },
  {
    id: "ideogram-character",
    name: "Ideogram Character",
    nameRu: "Ideogram Персонаж",
    category: "image",
    type: "character",
    description: "Generate consistent characters",
    descriptionRu: "Генерация консистентных персонажей",
    modelId: "ideogram/character",
    icon: "👤",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true },
      { name: "character_description", label: "Character Description", labelRu: "Описание персонажа", type: "textarea", required: false },
    ],
  },
  {
    id: "ideogram-character-edit",
    name: "Ideogram Character Edit",
    nameRu: "Ideogram Редактирование персонажа",
    category: "image",
    type: "character",
    description: "Edit character images",
    descriptionRu: "Редактирование персонажей",
    modelId: "ideogram/character-edit",
    icon: "✂️",
    inputFields: [
      { name: "image_url", label: "Character Image", labelRu: "Изображение персонажа", type: "file", required: true },
      { name: "prompt", label: "Edit Prompt", labelRu: "Промпт редактирования", type: "textarea", required: true },
    ],
  },
  {
    id: "ideogram-character-remix",
    name: "Ideogram Character Remix",
    nameRu: "Ideogram Ремикс персонажа",
    category: "image",
    type: "character",
    description: "Remix character styles",
    descriptionRu: "Ремикс стилей персонажа",
    modelId: "ideogram/character-remix",
    icon: "🔄",
    inputFields: [
      { name: "image_url", label: "Character Image", labelRu: "Изображение персонажа", type: "file", required: true },
      { name: "prompt", label: "Remix Prompt", labelRu: "Промпт ремикса", type: "textarea", required: true },
    ],
  },
  {
    id: "seedream-3",
    name: "Seedream 3.0",
    nameRu: "Seedream 3.0",
    category: "image",
    type: "text-to-image",
    description: "Creative image generation by Bytedance",
    descriptionRu: "Креативная генерация от Bytedance",
    modelId: "bytedance/seedream",
    icon: "🌱",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true },
      { name: "image_size", label: "Size", labelRu: "Размер", type: "select", required: false, options: [
        { value: "square_hd", label: "Square HD", labelRu: "Квадрат HD" },
        { value: "landscape_16_9", label: "Landscape", labelRu: "Альбом" },
        { value: "portrait_9_16", label: "Portrait", labelRu: "Портрет" },
      ], defaultValue: "square_hd" },
      { name: "guidance_scale", label: "Guidance", labelRu: "Сила", type: "slider", required: false, min: 1, max: 10, step: 0.5, defaultValue: 2.5 },
    ],
  },
  {
    id: "seedream-4",
    name: "Seedream 4.0",
    nameRu: "Seedream 4.0",
    category: "image",
    type: "text-to-image",
    description: "Enhanced creative generation",
    descriptionRu: "Улучшенная креативная генерация",
    modelId: "seedream-4.0",
    icon: "🌿",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true },
      { name: "image_size", label: "Size", labelRu: "Размер", type: "select", required: false, options: [
        { value: "square_hd", label: "Square HD", labelRu: "Квадрат HD" },
        { value: "landscape_16_9", label: "Landscape", labelRu: "Альбом" },
        { value: "portrait_9_16", label: "Portrait", labelRu: "Портрет" },
      ], defaultValue: "square_hd" },
    ],
  },
  {
    id: "seedream-4-5",
    name: "Seedream 4.5",
    nameRu: "Seedream 4.5",
    category: "image",
    type: "text-to-image",
    description: "Latest Seedream model",
    descriptionRu: "Новейшая модель Seedream",
    modelId: "seedream-4.5",
    icon: "🌳",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true },
      { name: "image_size", label: "Size", labelRu: "Размер", type: "select", required: false, options: [
        { value: "square_hd", label: "Square HD", labelRu: "Квадрат HD" },
        { value: "landscape_16_9", label: "Landscape", labelRu: "Альбом" },
        { value: "portrait_9_16", label: "Portrait", labelRu: "Портрет" },
      ], defaultValue: "square_hd" },
    ],
  },
  // === Upscale Models ===
  {
    id: "aura-sr",
    name: "Aura SR Upscaler",
    nameRu: "Aura SR Апскейлер",
    category: "image",
    type: "upscale",
    description: "AI-powered image upscaling",
    descriptionRu: "ИИ увеличение разрешения изображений",
    modelId: "fal/aura-sr",
    icon: "🔍",
    inputFields: [
      { name: "image_url", label: "Image", labelRu: "Изображение", type: "file", required: true },
      { name: "upscaling_factor", label: "Scale", labelRu: "Масштаб", type: "select", required: false, options: [
        { value: "2", label: "2x", labelRu: "2x" },
        { value: "4", label: "4x", labelRu: "4x" },
      ], defaultValue: "4" },
      { name: "creativity", label: "Creativity", labelRu: "Креативность", type: "slider", required: false, min: 0, max: 1, step: 0.1, defaultValue: 0 },
      { name: "resemblance", label: "Resemblance", labelRu: "Сходство", type: "slider", required: false, min: 0, max: 1, step: 0.1, defaultValue: 0.6 },
    ],
  },
  {
    id: "clarity-upscaler",
    name: "Clarity Upscaler",
    nameRu: "Clarity Апскейлер",
    category: "image",
    type: "upscale",
    description: "High-quality image upscaling with clarity enhancement",
    descriptionRu: "Высококачественное увеличение с улучшением чёткости",
    modelId: "fal/clarity-upscaler",
    icon: "✨",
    inputFields: [
      { name: "image_url", label: "Image", labelRu: "Изображение", type: "file", required: true },
      { name: "scale", label: "Scale", labelRu: "Масштаб", type: "select", required: false, options: [
        { value: "2", label: "2x", labelRu: "2x" },
        { value: "4", label: "4x", labelRu: "4x" },
      ], defaultValue: "2" },
      { name: "prompt", label: "Enhancement Prompt", labelRu: "Промпт улучшения", type: "textarea", required: false, placeholderRu: "Опционально: детали для улучшения" },
    ],
  },
  // === Background Removal Models ===
  {
    id: "bria-rmbg",
    name: "BRIA Background Removal",
    nameRu: "BRIA Удаление фона",
    category: "image",
    type: "background-removal",
    description: "Professional background removal",
    descriptionRu: "Профессиональное удаление фона",
    modelId: "fal/bria/rmbg",
    icon: "🧹",
    inputFields: [
      { name: "image_url", label: "Image", labelRu: "Изображение", type: "file", required: true },
    ],
  },
  {
    id: "birefnet-rmbg",
    name: "BiRefNet Background Removal",
    nameRu: "BiRefNet Удаление фона",
    category: "image",
    type: "background-removal",
    description: "High-resolution background removal",
    descriptionRu: "Удаление фона в высоком разрешении",
    modelId: "fal/birefnet",
    icon: "🎭",
    inputFields: [
      { name: "image_url", label: "Image", labelRu: "Изображение", type: "file", required: true },
      { name: "model", label: "Model", labelRu: "Модель", type: "select", required: false, options: [
        { value: "General", label: "General", labelRu: "Общая" },
        { value: "General-Lite", label: "General Lite", labelRu: "Общая лёгкая" },
        { value: "Portrait", label: "Portrait", labelRu: "Портрет" },
      ], defaultValue: "General" },
      { name: "operating_resolution", label: "Resolution", labelRu: "Разрешение обработки", type: "select", required: false, options: [
        { value: "1024x1024", label: "1024x1024", labelRu: "1024x1024" },
        { value: "2048x2048", label: "2048x2048", labelRu: "2048x2048" },
      ], defaultValue: "1024x1024" },
    ],
  },
  // === Flux Kontext Models ===
  {
    id: "flux-kontext-pro",
    name: "Flux Kontext Pro",
    nameRu: "Flux Kontext Pro",
    category: "image",
    type: "text-to-image",
    description: "Balanced performance image generation",
    descriptionRu: "Сбалансированная генерация изображений",
    modelId: "flux-kontext-pro",
    icon: "🎨",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true, placeholderRu: "Опишите изображение..." },
      { name: "aspect_ratio", label: "Aspect Ratio", labelRu: "Соотношение сторон", type: "select", required: false, options: [
        { value: "1:1", label: "1:1 Square", labelRu: "1:1 Квадрат" },
        { value: "16:9", label: "16:9 Widescreen", labelRu: "16:9 Широкий" },
        { value: "9:16", label: "9:16 Mobile", labelRu: "9:16 Мобильный" },
        { value: "4:3", label: "4:3 Standard", labelRu: "4:3 Стандарт" },
        { value: "3:4", label: "3:4 Portrait", labelRu: "3:4 Портрет" },
        { value: "21:9", label: "21:9 Cinematic", labelRu: "21:9 Кино" },
      ], defaultValue: "1:1" },
      { name: "prompt_upsampling", label: "Prompt Enhancement", labelRu: "Улучшение промпта", type: "checkbox", required: false, defaultValue: false },
      { name: "safety_tolerance", label: "Safety Tolerance", labelRu: "Уровень безопасности", type: "slider", required: false, min: 0, max: 6, step: 1, defaultValue: 2 },
    ],
  },
  {
    id: "flux-kontext-max",
    name: "Flux Kontext Max",
    nameRu: "Flux Kontext Max",
    category: "image",
    type: "text-to-image",
    description: "Enhanced quality for complex scenes",
    descriptionRu: "Улучшенное качество для сложных сцен",
    modelId: "flux-kontext-max",
    icon: "✨",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true, placeholderRu: "Опишите изображение..." },
      { name: "aspect_ratio", label: "Aspect Ratio", labelRu: "Соотношение сторон", type: "select", required: false, options: [
        { value: "1:1", label: "1:1 Square", labelRu: "1:1 Квадрат" },
        { value: "16:9", label: "16:9 Widescreen", labelRu: "16:9 Широкий" },
        { value: "9:16", label: "9:16 Mobile", labelRu: "9:16 Мобильный" },
        { value: "4:3", label: "4:3 Standard", labelRu: "4:3 Стандарт" },
        { value: "3:4", label: "3:4 Portrait", labelRu: "3:4 Портрет" },
        { value: "21:9", label: "21:9 Cinematic", labelRu: "21:9 Кино" },
      ], defaultValue: "1:1" },
      { name: "prompt_upsampling", label: "Prompt Enhancement", labelRu: "Улучшение промпта", type: "checkbox", required: false, defaultValue: true },
      { name: "safety_tolerance", label: "Safety Tolerance", labelRu: "Уровень безопасности", type: "slider", required: false, min: 0, max: 6, step: 1, defaultValue: 2 },
    ],
  },
  {
    id: "flux-kontext-edit",
    name: "Flux Kontext Edit",
    nameRu: "Flux Kontext Редактирование",
    category: "image",
    type: "image-edit",
    description: "Edit existing images with AI",
    descriptionRu: "Редактирование изображений с помощью ИИ",
    modelId: "flux-kontext-edit",
    icon: "✏️",
    inputFields: [
      { name: "image_url", label: "Image", labelRu: "Изображение", type: "file", required: true },
      { name: "prompt", label: "Edit Prompt", labelRu: "Промпт редактирования", type: "textarea", required: true, placeholderRu: "Опишите изменения..." },
      { name: "safety_tolerance", label: "Safety Tolerance", labelRu: "Уровень безопасности", type: "slider", required: false, min: 0, max: 2, step: 1, defaultValue: 1 },
    ],
  },
];

// ==================== Video Models ====================

export const VIDEO_MODELS: KieModel[] = [
  {
    id: "sora2-pro-t2v",
    name: "Sora2 Pro Text-to-Video",
    nameRu: "Sora2 Pro Текст-в-Видео",
    category: "video",
    type: "text-to-video",
    description: "State-of-the-art video generation from text",
    descriptionRu: "Передовая генерация видео из текста",
    modelId: "sora-2-pro-text-to-video",
    icon: "🎬",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true, placeholderRu: "Опишите видео..." },
      { name: "aspect_ratio", label: "Aspect Ratio", labelRu: "Соотношение", type: "select", required: false, options: [
        { value: "landscape", label: "16:9", labelRu: "16:9 Альбом" },
        { value: "portrait", label: "9:16", labelRu: "9:16 Портрет" },
        { value: "square", label: "1:1", labelRu: "1:1 Квадрат" },
      ], defaultValue: "landscape" },
      { name: "resolution", label: "Resolution", labelRu: "Разрешение", type: "select", required: false, options: [
        { value: "720p", label: "720p", labelRu: "720p HD" },
        { value: "1080p", label: "1080p", labelRu: "1080p Full HD" },
        { value: "2k", label: "2K", labelRu: "2K" },
        { value: "4k", label: "4K", labelRu: "4K Ultra HD" },
      ], defaultValue: "1080p" },
      { name: "n_frames", label: "Duration", labelRu: "Длительность", type: "select", required: false, options: [
        { value: "5", label: "5 sec", labelRu: "5 сек" },
        { value: "10", label: "10 sec", labelRu: "10 сек" },
        { value: "15", label: "15 sec", labelRu: "15 сек" },
      ], defaultValue: "5" },
      { name: "remove_watermark", label: "Remove Watermark", labelRu: "Убрать водяной знак", type: "checkbox", required: false, defaultValue: true },
    ],
  },
  {
    id: "sora2-pro-i2v",
    name: "Sora2 Pro Image-to-Video",
    nameRu: "Sora2 Pro Фото-в-Видео",
    category: "video",
    type: "image-to-video",
    description: "Animate images into videos",
    descriptionRu: "Анимация изображений в видео",
    modelId: "sora-2-pro-image-to-video",
    icon: "🎞️",
    inputFields: [
      { name: "image_url", label: "Image", labelRu: "Изображение", type: "file", required: true },
      { name: "prompt", label: "Animation Prompt", labelRu: "Промпт анимации", type: "textarea", required: true },
      { name: "aspect_ratio", label: "Aspect Ratio", labelRu: "Соотношение", type: "select", required: false, options: [
        { value: "landscape", label: "16:9", labelRu: "16:9 Альбом" },
        { value: "portrait", label: "9:16", labelRu: "9:16 Портрет" },
        { value: "square", label: "1:1", labelRu: "1:1 Квадрат" },
      ], defaultValue: "landscape" },
      { name: "resolution", label: "Resolution", labelRu: "Разрешение", type: "select", required: false, options: [
        { value: "720p", label: "720p", labelRu: "720p HD" },
        { value: "1080p", label: "1080p", labelRu: "1080p Full HD" },
        { value: "4k", label: "4K", labelRu: "4K Ultra HD" },
      ], defaultValue: "1080p" },
    ],
  },
  {
    id: "sora2-fast-t2v",
    name: "Sora2 Fast Text-to-Video",
    nameRu: "Sora2 Fast Текст-в-Видео",
    category: "video",
    type: "text-to-video",
    description: "Fast video generation",
    descriptionRu: "Быстрая генерация видео",
    modelId: "sora-2-fast-text-to-video",
    icon: "⚡",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true },
      { name: "aspect_ratio", label: "Aspect Ratio", labelRu: "Соотношение", type: "select", required: false, options: [
        { value: "landscape", label: "16:9", labelRu: "16:9 Альбом" },
        { value: "portrait", label: "9:16", labelRu: "9:16 Портрет" },
        { value: "square", label: "1:1", labelRu: "1:1 Квадрат" },
      ], defaultValue: "landscape" },
      { name: "resolution", label: "Resolution", labelRu: "Разрешение", type: "select", required: false, options: [
        { value: "720p", label: "720p", labelRu: "720p" },
        { value: "1080p", label: "1080p", labelRu: "1080p Full HD" },
      ], defaultValue: "1080p" },
    ],
  },
  {
    id: "kling-v2-1-pro",
    name: "Kling v2.1 Pro",
    nameRu: "Kling v2.1 Pro",
    category: "video",
    type: "image-to-video",
    description: "High-quality video generation",
    descriptionRu: "Высококачественная генерация видео",
    modelId: "kling/v2-1-pro",
    icon: "🎥",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true },
      { name: "image_url", label: "Start Image (optional)", labelRu: "Начальное изображение", type: "file", required: false },
      { name: "duration", label: "Duration", labelRu: "Длительность", type: "select", required: false, options: [
        { value: "5", label: "5 sec", labelRu: "5 сек" },
        { value: "10", label: "10 sec", labelRu: "10 сек" },
      ], defaultValue: "5" },
      { name: "negative_prompt", label: "Negative Prompt", labelRu: "Негативный промпт", type: "textarea", required: false },
      { name: "cfg_scale", label: "CFG Scale", labelRu: "CFG Масштаб", type: "slider", required: false, min: 0, max: 1, step: 0.1, defaultValue: 0.5 },
    ],
  },
  {
    id: "kling-v2-5-pro",
    name: "Kling v2.5 Pro",
    nameRu: "Kling v2.5 Pro",
    category: "video",
    type: "image-to-video",
    description: "Latest Kling model",
    descriptionRu: "Новейшая модель Kling",
    modelId: "kling/v2-5-pro",
    icon: "🎦",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true },
      { name: "image_url", label: "Start Image (optional)", labelRu: "Начальное изображение", type: "file", required: false },
      { name: "duration", label: "Duration", labelRu: "Длительность", type: "select", required: false, options: [
        { value: "5", label: "5 sec", labelRu: "5 сек" },
        { value: "10", label: "10 sec", labelRu: "10 сек" },
      ], defaultValue: "5" },
    ],
  },
  {
    id: "hailuo-i2v-pro",
    name: "Hailuo Image-to-Video Pro",
    nameRu: "Hailuo Фото-в-Видео Pro",
    category: "video",
    type: "image-to-video",
    description: "Transform images to videos",
    descriptionRu: "Трансформация изображений в видео",
    modelId: "hailuo/2-3-image-to-video-pro",
    icon: "🌊",
    inputFields: [
      { name: "image_url", label: "Image", labelRu: "Изображение", type: "file", required: true },
      { name: "prompt", label: "Animation Prompt", labelRu: "Промпт анимации", type: "textarea", required: true },
      { name: "duration", label: "Duration", labelRu: "Длительность", type: "select", required: false, options: [
        { value: "4", label: "4 sec", labelRu: "4 сек" },
        { value: "6", label: "6 sec", labelRu: "6 сек" },
      ], defaultValue: "6" },
      { name: "resolution", label: "Resolution", labelRu: "Разрешение", type: "select", required: false, options: [
        { value: "720P", label: "720p", labelRu: "720p HD" },
        { value: "1080P", label: "1080p", labelRu: "1080p Full HD" },
        { value: "2K", label: "2K", labelRu: "2K" },
      ], defaultValue: "1080P" },
    ],
  },
  {
    id: "hailuo-t2v",
    name: "Hailuo Text-to-Video",
    nameRu: "Hailuo Текст-в-Видео",
    category: "video",
    type: "text-to-video",
    description: "Text to video generation",
    descriptionRu: "Генерация видео из текста",
    modelId: "hailuo/2-3-text-to-video",
    icon: "🌈",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true },
      { name: "duration", label: "Duration", labelRu: "Длительность", type: "select", required: false, options: [
        { value: "4", label: "4 sec", labelRu: "4 сек" },
        { value: "6", label: "6 sec", labelRu: "6 сек" },
      ], defaultValue: "6" },
      { name: "resolution", label: "Resolution", labelRu: "Разрешение", type: "select", required: false, options: [
        { value: "720P", label: "720p", labelRu: "720p HD" },
        { value: "1080P", label: "1080p", labelRu: "1080p Full HD" },
        { value: "2K", label: "2K", labelRu: "2K" },
      ], defaultValue: "1080P" },
    ],
  },
  // === Runway Models ===
  {
    id: "runway-t2v",
    name: "Runway Text-to-Video",
    nameRu: "Runway Текст-в-Видео",
    category: "video",
    type: "text-to-video",
    description: "Transform text prompts into dynamic video content",
    descriptionRu: "Создание видео из текстовых описаний",
    modelId: "runway/text-to-video",
    icon: "🎬",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true, placeholderRu: "Опишите видео с деталями движения, стиля, освещения..." },
      { name: "duration", label: "Duration", labelRu: "Длительность", type: "select", required: false, options: [
        { value: "5", label: "5 sec (720p/1080p)", labelRu: "5 сек (720p/1080p)" },
        { value: "10", label: "10 sec (720p only)", labelRu: "10 сек (только 720p)" },
      ], defaultValue: "5" },
      { name: "quality", label: "Quality", labelRu: "Качество", type: "select", required: false, options: [
        { value: "720p", label: "720p HD", labelRu: "720p HD" },
        { value: "1080p", label: "1080p Full HD", labelRu: "1080p Full HD" },
      ], defaultValue: "720p" },
      { name: "aspectRatio", label: "Aspect Ratio", labelRu: "Соотношение сторон", type: "select", required: false, options: [
        { value: "16:9", label: "16:9 Widescreen", labelRu: "16:9 Широкий" },
        { value: "9:16", label: "9:16 Vertical", labelRu: "9:16 Вертикальный" },
        { value: "1:1", label: "1:1 Square", labelRu: "1:1 Квадрат" },
        { value: "4:3", label: "4:3 Traditional", labelRu: "4:3 Традиционный" },
        { value: "3:4", label: "3:4 Portrait", labelRu: "3:4 Портрет" },
      ], defaultValue: "16:9" },
    ],
  },
  {
    id: "runway-i2v",
    name: "Runway Image-to-Video",
    nameRu: "Runway Фото-в-Видео",
    category: "video",
    type: "image-to-video",
    description: "Animate existing images into engaging videos",
    descriptionRu: "Анимация изображений в видео",
    modelId: "runway/image-to-video",
    icon: "🎞️",
    inputFields: [
      { name: "image_url", label: "Image", labelRu: "Изображение", type: "file", required: true },
      { name: "prompt", label: "Animation Prompt", labelRu: "Промпт анимации", type: "textarea", required: true, placeholderRu: "Опишите движение персонажа..." },
      { name: "duration", label: "Duration", labelRu: "Длительность", type: "select", required: false, options: [
        { value: "5", label: "5 sec", labelRu: "5 сек" },
        { value: "10", label: "10 sec (720p only)", labelRu: "10 сек (только 720p)" },
      ], defaultValue: "5" },
      { name: "quality", label: "Quality", labelRu: "Качество", type: "select", required: false, options: [
        { value: "720p", label: "720p HD", labelRu: "720p HD" },
        { value: "1080p", label: "1080p Full HD", labelRu: "1080p Full HD" },
      ], defaultValue: "720p" },
      { name: "aspectRatio", label: "Aspect Ratio", labelRu: "Соотношение сторон", type: "select", required: false, options: [
        { value: "16:9", label: "16:9 Widescreen", labelRu: "16:9 Широкий" },
        { value: "9:16", label: "9:16 Vertical", labelRu: "9:16 Вертикальный" },
        { value: "1:1", label: "1:1 Square", labelRu: "1:1 Квадрат" },
      ], defaultValue: "16:9" },
    ],
  },
  // === Luma Models ===
  {
    id: "luma-modify",
    name: "Luma Video Modify",
    nameRu: "Luma Модификация видео",
    category: "video",
    type: "video-modify",
    description: "Transform existing videos with AI-powered modifications",
    descriptionRu: "Трансформация видео с помощью ИИ",
    modelId: "luma/modify",
    icon: "🔮",
    inputFields: [
      { name: "video_url", label: "Video", labelRu: "Видео", type: "file", required: true, accept: "video/*" },
      { name: "prompt", label: "Modification Prompt", labelRu: "Промпт модификации", type: "textarea", required: true, placeholderRu: "Опишите желаемые изменения в видео..." },
      { name: "watermark", label: "Add Watermark", labelRu: "Добавить водяной знак", type: "checkbox", required: false, defaultValue: false },
    ],
  },
  // === Veo 3.1 Models ===
  {
    id: "veo3-t2v",
    name: "Veo 3.1 Text-to-Video",
    nameRu: "Veo 3.1 Текст-в-Видео",
    category: "video",
    type: "text-to-video",
    description: "Google's high-quality video generation from text",
    descriptionRu: "Высококачественная генерация видео от Google",
    modelId: "veo3",
    icon: "🎥",
    inputFields: [
      { name: "prompt", label: "Prompt", labelRu: "Промпт", type: "textarea", required: true, placeholderRu: "Опишите видео подробно..." },
      { name: "aspectRatio", label: "Aspect Ratio", labelRu: "Соотношение сторон", type: "select", required: false, options: [
        { value: "16:9", label: "16:9 Widescreen", labelRu: "16:9 Широкий" },
        { value: "9:16", label: "9:16 Vertical", labelRu: "9:16 Вертикальный" },
        { value: "1:1", label: "1:1 Square", labelRu: "1:1 Квадрат" },
      ], defaultValue: "16:9" },
    ],
  },
  {
    id: "veo3-i2v",
    name: "Veo 3.1 Image-to-Video",
    nameRu: "Veo 3.1 Фото-в-Видео",
    category: "video",
    type: "image-to-video",
    description: "Bring static images to life with Veo 3.1",
    descriptionRu: "Оживление статичных изображений с Veo 3.1",
    modelId: "veo3",
    icon: "🎬",
    inputFields: [
      { name: "image_url", label: "Image", labelRu: "Изображение", type: "file", required: true },
      { name: "prompt", label: "Animation Prompt", labelRu: "Промпт анимации", type: "textarea", required: true, placeholderRu: "Опишите движение..." },
      { name: "aspectRatio", label: "Aspect Ratio", labelRu: "Соотношение сторон", type: "select", required: false, options: [
        { value: "16:9", label: "16:9 Widescreen", labelRu: "16:9 Широкий" },
        { value: "9:16", label: "9:16 Vertical", labelRu: "9:16 Вертикальный" },
        { value: "1:1", label: "1:1 Square", labelRu: "1:1 Квадрат" },
      ], defaultValue: "16:9" },
    ],
  },
];

// ==================== Audio Models ====================

export const AUDIO_MODELS: KieModel[] = [
  {
    id: "elevenlabs-tts",
    name: "ElevenLabs TTS Turbo 2.5",
    nameRu: "ElevenLabs Озвучка Turbo 2.5",
    category: "audio",
    type: "text-to-speech",
    description: "High-quality text-to-speech",
    descriptionRu: "Высококачественная озвучка текста",
    modelId: "elevenlabs/text-to-speech-turbo-2-5",
    icon: "🎙️",
    inputFields: [
      { name: "text", label: "Text", labelRu: "Текст", type: "textarea", required: true, placeholderRu: "Введите текст для озвучки..." },
      { name: "voice", label: "Voice", labelRu: "Голос", type: "select", required: false, options: [
        { value: "Rachel", label: "Rachel (Female)", labelRu: "Rachel (Женский)" },
        { value: "Drew", label: "Drew (Male)", labelRu: "Drew (Мужской)" },
        { value: "Clyde", label: "Clyde (Male)", labelRu: "Clyde (Мужской)" },
        { value: "Paul", label: "Paul (Male)", labelRu: "Paul (Мужской)" },
        { value: "Domi", label: "Domi (Female)", labelRu: "Domi (Женский)" },
        { value: "Dave", label: "Dave (Male)", labelRu: "Dave (Мужской)" },
        { value: "Fin", label: "Fin (Male)", labelRu: "Fin (Мужской)" },
        { value: "Sarah", label: "Sarah (Female)", labelRu: "Sarah (Женский)" },
        { value: "Antoni", label: "Antoni (Male)", labelRu: "Antoni (Мужской)" },
        { value: "Thomas", label: "Thomas (Male)", labelRu: "Thomas (Мужской)" },
        { value: "Charlie", label: "Charlie (Male)", labelRu: "Charlie (Мужской)" },
        { value: "Emily", label: "Emily (Female)", labelRu: "Emily (Женский)" },
      ], defaultValue: "Rachel" },
      { name: "stability", label: "Stability", labelRu: "Стабильность", type: "slider", required: false, min: 0, max: 1, step: 0.1, defaultValue: 0.5 },
      { name: "similarity_boost", label: "Clarity", labelRu: "Чёткость", type: "slider", required: false, min: 0, max: 1, step: 0.1, defaultValue: 0.75 },
      { name: "speed", label: "Speed", labelRu: "Скорость", type: "slider", required: false, min: 0.5, max: 2, step: 0.1, defaultValue: 1 },
    ],
  },
  // === Suno Music Models ===
  {
    id: "suno-v5",
    name: "Suno V5 Music",
    nameRu: "Suno V5 Музыка",
    category: "audio",
    type: "text-to-music",
    description: "Generate original music from text descriptions",
    descriptionRu: "Генерация оригинальной музыки из текста",
    modelId: "V5",
    icon: "🎵",
    inputFields: [
      { name: "prompt", label: "Music Description", labelRu: "Описание музыки", type: "textarea", required: true, placeholderRu: "Опишите желаемую музыку: жанр, настроение, темп..." },
      { name: "custom_mode", label: "Custom Mode", labelRu: "Расширенный режим", type: "checkbox", required: false, defaultValue: false },
      { name: "style", label: "Style", labelRu: "Стиль", type: "text", required: false, placeholderRu: "Pop, Rock, Jazz, Classical..." },
      { name: "title", label: "Title", labelRu: "Название", type: "text", required: false, placeholderRu: "Название трека" },
      { name: "instrumental", label: "Instrumental Only", labelRu: "Только инструментал", type: "checkbox", required: false, defaultValue: false },
    ],
  },
  {
    id: "suno-v4-5",
    name: "Suno V4.5 Music",
    nameRu: "Suno V4.5 Музыка",
    category: "audio",
    type: "text-to-music",
    description: "High-quality music generation",
    descriptionRu: "Высококачественная генерация музыки",
    modelId: "V4_5",
    icon: "🎶",
    inputFields: [
      { name: "prompt", label: "Music Description", labelRu: "Описание музыки", type: "textarea", required: true, placeholderRu: "Опишите желаемую музыку..." },
      { name: "custom_mode", label: "Custom Mode", labelRu: "Расширенный режим", type: "checkbox", required: false, defaultValue: false },
      { name: "style", label: "Style", labelRu: "Стиль", type: "text", required: false },
      { name: "title", label: "Title", labelRu: "Название", type: "text", required: false },
      { name: "instrumental", label: "Instrumental Only", labelRu: "Только инструментал", type: "checkbox", required: false, defaultValue: false },
      { name: "boost_style", label: "Boost Style", labelRu: "Усилить стиль", type: "checkbox", required: false, defaultValue: false },
    ],
  },
  {
    id: "suno-lyrics",
    name: "Suno Lyrics Generator",
    nameRu: "Suno Генератор текстов",
    category: "audio",
    type: "lyrics-generation",
    description: "Generate creative lyrics from prompts",
    descriptionRu: "Генерация текстов песен из описания",
    modelId: "suno/lyrics",
    icon: "📝",
    inputFields: [
      { name: "prompt", label: "Lyrics Theme", labelRu: "Тема текста", type: "textarea", required: true, placeholderRu: "Опишите тему и настроение песни..." },
    ],
  },
  {
    id: "suno-extend",
    name: "Suno Music Extend",
    nameRu: "Suno Продление музыки",
    category: "audio",
    type: "music-extend",
    description: "Extend existing music tracks seamlessly",
    descriptionRu: "Плавное продление музыкальных треков",
    modelId: "suno/extend",
    icon: "🔄",
    inputFields: [
      { name: "audio_url", label: "Audio File", labelRu: "Аудио файл", type: "file", required: true, accept: "audio/*" },
      { name: "prompt", label: "Extension Description", labelRu: "Описание продления", type: "textarea", required: false, placeholderRu: "Как продолжить трек..." },
    ],
  },
  {
    id: "suno-cover",
    name: "Suno Cover Song",
    nameRu: "Suno Кавер",
    category: "audio",
    type: "music-cover",
    description: "Transform uploaded audio into new styles",
    descriptionRu: "Трансформация аудио в новые стили",
    modelId: "suno/cover",
    icon: "🎤",
    inputFields: [
      { name: "audio_url", label: "Audio File", labelRu: "Аудио файл", type: "file", required: true, accept: "audio/*" },
      { name: "style", label: "Target Style", labelRu: "Целевой стиль", type: "text", required: true, placeholderRu: "Jazz, Rock, Electronic..." },
    ],
  },
  {
    id: "suno-vocals-separate",
    name: "Suno Vocal Separator",
    nameRu: "Suno Разделение вокала",
    category: "audio",
    type: "vocal-separation",
    description: "Separate vocals and instrumentals from music",
    descriptionRu: "Разделение вокала и инструментала",
    modelId: "suno/separate-vocals",
    icon: "🎧",
    inputFields: [
      { name: "audio_url", label: "Audio File", labelRu: "Аудио файл", type: "file", required: true, accept: "audio/*" },
    ],
  },
];

// ==================== All Models ====================

export const ALL_MODELS: KieModel[] = [
  ...IMAGE_MODELS,
  ...VIDEO_MODELS,
  ...AUDIO_MODELS,
];

// ==================== Helper Functions ====================

export function getModelById(id: string): KieModel | undefined {
  return ALL_MODELS.find((m) => m.id === id);
}

export function getModelByModelId(modelId: string): KieModel | undefined {
  return ALL_MODELS.find((m) => m.modelId === modelId);
}

export function getModelsByCategory(category: "image" | "video" | "audio"): KieModel[] {
  return ALL_MODELS.filter((m) => m.category === category);
}

export function getModelsByType(type: string): KieModel[] {
  return ALL_MODELS.filter((m) => m.type === type);
}
